application: shopo-1052
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/.*
  script: main.app

- url: /import/.*
  script: import.app

- url: /importers/.*
  script: import.app

- url: (.*)/
  static_files: app\1/index.html
  upload: app

- url: (.*)
  static_files: app\1
  upload: app

libraries:
- name: webapp2
  version: "2.5.2"
